Cartify_Shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from cart.views import *
from checkout.views import *
from product.views import *
from wishlist.views import *
from admin_panel.views import *
from home.views import *
from admin_panel.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('home.urls')),
    path('products/',include('product.urls')),
    path('admin-panel/',include('admin_panel.urls')),
    path('add-to-cart/',add_to_cart ,name='add_to_cart'),
    path('add-to-wishlist/',add_to_wishlist ,name='add_to_wishlist'),
    path('delete-from-wishlist/',delete_from_wishlist ,name='delete_from_wishlist'),
    path('update-shippingaddress/', updateshippingaddress ,name='updateshippingaddress'),  
    path('cart/',include('cart.urls')),
    path('checkout/',include('checkout.urls')),
    path('filter-data', filter_data ,name='filter_data'),  
    path('sort-data', sort_data ,name='sort_data'),  
    path('order/',include('orders.urls')),
    path('update-order/',update_order,name='update_order'),
    path('update-coupon/',update_coupon,name='update_coupon'),
    path('wishlist/',include('wishlist.urls')),
    path('proceed-to-pay',razorpaycheck,name='razorpaycheck'),
    path('payment-method/',payment_method,name='payment_method'),
    path('paypal-method/',paypal_method,name='paypal_method'),
    path('update-profile/',update_profile,name='update_profile'),
    path('update-admin-profile/',update_admin_profile,name='update_admin_profile'),
    path('add-offer/',add_offer,name='add_offer'),
    path('product-list',product_list,name="product_list"),
    path('search-product',searchproduct,name='searchproduct'),
    path('admin-panel-products',admin_panel_products,name="admin_panel_products"),
    path('admin-panel-customers',admin_panel_customers,name="admin_panel_customers"),
    path('admin-panel-coupons',coupons_list_admin,name="coupons_list_admin"),
    path('admin-panel-category',category_list_admin,name="category_list_admin"),
    path('admin-panel-offers',offers_list_admin,name="offers_list_admin"),
    path('update-offer/',update_offer,name='update_offer'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    
urlpatterns+=staticfiles_urlpatterns()

cart/urls.py
from django.urls import path
from cart.views import *


urlpatterns = [
    path('', cartpage ,name='cartpage'),  
    path('delete-cartitem <uuid:uid>',product_delete,name='cartitem_delete'),
    path('remove-coupon <uuid:uid>', remove_coupon,name='remove_coupon'),
    

]

checkout/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', checkout ,name='checkout'),  
    path('address', add_address ,name='add_address'),  
    path('edit-address <uuid:uid>', edit_address ,name='edit_address'),  
    path('delete-address <uuid:uid>', delete_addresss ,name='delete_address'),
    path('edit-address ', edit_session_address ,name='edit_session_address'),  
    path('delete-address ', delete_session_address ,name='delete_session_address'),
    path('paypal-payment',paypal_payment,name='paypal_payment'),
    path('payment', paymentpage ,name='paymentpage'),  
    

]

checkout/models.py
from django.db import models
from accounts.models import User
from base.models import BaseModel
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

class Address(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    pincode = models.CharField(max_length=10)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def save(self, *args, **kwargs):
        from cart.models import Order
        
        if self.is_default and self.user is not None and self.user.is_authenticated:
            # Set all other Address objects related to the same User instance to is_default=False
            self.__class__.objects.filter(user=self.user).exclude(pk=self.pk).update(is_default=False)
            order = Order.objects.get(customer=self.user.customer,complete=False)
            order.shipping_address=self
            order.save()
        super(Address, self).save(*args, **kwargs)
    
@receiver(post_save, sender=Address)
def set_default_address(sender, instance, **kwargs):
    from cart.models import Order

    # Check if there are any other Address objects for the same user
    other_addresses = Address.objects.filter(user=instance.user).exclude(pk=instance.pk)
    
    # If no other Address objects exist, set this one as the default
    if not other_addresses.exists() and not instance.is_default:
        instance.is_default = True
        order = Order.objects.get(customer=instance.user.customer,complete=False)
        order.shipping_address=instance
        order.save()
        instance.save()
    
    # If the default Address object was deleted, set the next available one as the default
    if not Address.objects.filter(user=instance.user, is_default=True).exists():
        next_available = Address.objects.filter(user=instance.user).order_by('created_at').first()
        if next_available:
            next_available.is_default = True
            order = Order.objects.get(customer=instance.user.customer,complete=False)
            order.shipping_address=next_available
            order.save()
            next_available.save()

@receiver(post_delete, sender=Address)
def delete_default_address(sender, instance, **kwargs):
    from cart.models import Order

    # If the default Address object was deleted, set the next available one as the default
    if instance.is_default:
        next_available = Address.objects.filter(user=instance.user).order_by('created_at').first()
        if next_available:
            next_available.is_default = True
            order = Order.objects.get(customer=instance.user.customer,complete=False)
            order.shipping_address=next_available
            order.save()
            next_available.save()

checkout/views.py
from django.http import  Http404,HttpResponse,HttpResponseRedirect,JsonResponse
from django.shortcuts import redirect,render
from django.contrib import messages
from product.models import *
from cart.models import *
from accounts.models import User
from django.contrib.auth.decorators import login_required
from .forms import *
import json
from datetime import datetime, timedelta
from django.utils import timezone
import random
from cart.utils import Cookie_cart,Cart_address
import uuid
from wishlist.models import *

# Create your views here.
def checkout(request):
    flag=False
    if request.user.is_superuser:
            return redirect('/accounts/logout')
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.user.is_otp_verified:
            if request.user.is_blocked:
                messages.warning(request,"Account Blocked !!")
                return redirect('/accounts/logout')
            else:
                customer=request.user.customer
                customer.name=request.user.first_name
                customer.save()
                flag=True
                try:
                    order=Order.objects.get(customer=customer,complete=False)
                    items=order.orderitem_set.all()
                    if not items:
                        Order.objects.get(customer=customer,complete=False).delete()
                        messages.warning(request,"Your cart is empty, cartify some !!")

                        return redirect('/')
                except:
                    return redirect('/')
                for item in items:
                    if item.quantity>item.product_variant.quantity:
                        OrderItem.objects.get(uid=item.uid).delete()
                        messages.success(request,"Product removed as it sold out !!")
                no_items=OrderItem.get_total_orderItems(request.user)
                address=Address.objects.filter(user=request.user)

                context={
                    'items':items,
                    'order':order,
                    'no_items':no_items,
                    'address':address,
                    'flag':flag,
                }
                available_offers={}
                for item in items:
                    available_offers[item]=[]
                offer_discount=0
                greatestoffer=None
                for item in items:
                    if item.product.offer:
                        available_offers[item].append(item.product.offer)
                    if item.product.category.offer:
                        available_offers[item].append(item.product.category.offer)
                    if item.product.brand.first().offer:
                        available_offers[item].append(item.product.brand.first().offer)
                if available_offers:
                    for item,offers in available_offers.items():
                        for offer in offers:
                            if offer.discount>offer_discount:
                                offer_discount=offer.discount
                                greatestoffer=offer
                context['offer']=greatestoffer
                
                item_count=Wishlist.get_total_WishlistItems()
                context['item_count']=item_count
                if order:  
                    return render(request,'checkout/checkout.html',context)
                else:
                    return redirect('/')
        else:
            return redirect('/accounts/logout')
    else:
        cookieData=Cookie_cart(request)
        items=cookieData['items']
        order=cookieData['order']
        no_items=cookieData['no_items']
        item_count=cookieData['item_count']
        address=[]

        context={
            'items':items,
            'order':order,
            'no_items':no_items,
            'flag':flag,
            'address':address,
             'item_count':item_count,
            
        }
        context['item_count']=0
        if 'add' in request.session:
    
            add= request.session['add']
            add['uid']=uuid.UUID(add['uid'])
            address.append(add)
            context['address']=address
        

        if not items:
            messages.warning(request,"Your cart is empty, cartify some !!")
            return redirect('/')
        return render(request,'checkout/checkout.html',context)     

def add_address(request):
    context={}
    flag=False
    context['flag']=flag
    if request.user.is_superuser:
         return redirect('/accounts/logout')
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.user.is_otp_verified:
            if request.user.is_blocked:
                messages.warning(request,"Account Blocked !!")
                return redirect('/accounts/logout')
            else:
                order, created=Order.objects.get_or_create(customer=request.user.customer,complete=False)
                no_items=OrderItem.get_total_orderItems(request.user)
                context['no_items']=no_items
                item_count=Wishlist.get_total_WishlistItems()
                context['item_count']=item_count
                flag=True
                
    
        if request.method == 'POST':
            form = AddressForm(request.POST)
            if form.is_valid():
                form.clean_pincode()
                address = form.save(commit=False)
                
                if request.user.is_authenticated:
                    address.user = request.user  # Assign the current user to the address
                    address.save()
                else:
                    messages.warning(request,"Please Login to continue!!")
                return redirect('/checkout') 
            else:
                # Render the same form page with the invalid form data
                context = {'form': form, 'form_data': request.POST}
                return render(request, 'checkout/address.html', context)
        else:
            form = AddressForm()
            context['form']=form
        return render(request,'checkout/address.html',context)
    else:
        cookieData=Cookie_cart(request)
        items=cookieData['items']
        order=cookieData['order']
        no_items=cookieData['no_items']

        context={
            'items':items,
            'order':order,
            'no_items':no_items,
            'flag':flag,
           
        }
        if request.method == 'POST':
            add=Cart_address(request)
            if not add['pincode'].isdigit() or len(add['pincode']) != 6:
                context['address'] = add
                messages.warning(request,"Invalid entry for pincode !!")
                return render(request,'checkout/guestaddress.html',context)
            if not add['phone'].isdigit() or len(add['phone']) != 10:
                context['address'] = add
                messages.warning(request,"Invalid phonenumber !!")
                return render(request,'checkout/guestaddress.html',context)
            address=[]
            address.append(add)
            request.session['add']=add
            context['address']=address
            return render(request,'checkout/checkout.html',context)
        else:
            return render(request,'checkout/guestaddress.html',context)
def edit_address(request,uid):
    if request.user.is_superuser:
         return redirect('/accounts/logout')
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.user.is_otp_verified:
            if request.user.is_blocked:
                messages.warning(request,"Account Blocked !!")
                return redirect('/accounts/logout')
            else:
                context={}
                no_items=OrderItem.get_total_orderItems(request.user)
                context['no_items']=no_items
                item_count=Wishlist.get_total_WishlistItems()
                context['item_count']=item_count
                address=Address.objects.get(uid=uid)

                if request.method == 'POST':
                    form = AddressForm(request.POST, instance=address)
                    
                    if form.is_valid():
                        form.save()
                        
                        return redirect('/checkout/')
                else:
                    form = AddressForm(instance=address)
                    context['form']=form
                
                return render(request,'checkout/address.html',context)
    else:
        return redirect('/checkout/')
def edit_session_address(request):
    context={}
    if request.user.is_superuser:
         return redirect('/accounts/logout')
    if 'add' in request.session:
        context['address'] = request.session['add']
    if request.method == 'POST':
            add=Cart_address(request)
            request.session['add']=add
            context['address'] = request.session['add']
            return redirect('/checkout/')
    return render(request,'checkout/guestaddress.html',context)
def delete_addresss(request,uid):
    Address.objects.get(uid=uid).delete()
    messages.success(request,"Address Deleted !!")
    return redirect('/checkout/')
def delete_session_address(request):
    del request.session['add']
    return redirect('/checkout/')
def updateshippingaddress(request):
    data=json.loads(request.body)
    address_uid=data['address_uid']
    if request.user.is_authenticated:
        customer=request.user.customer
        order=Order.objects.get(customer=customer,complete=False)
        address=Address.objects.get(uid=address_uid)
        order.shipping_address=address
        order.save()
        return JsonResponse('address added',safe=False)
    else:
        return JsonResponse('Need to login to continue',safe=False)
def paymentpage(request):
    flag=False
    if request.user.is_superuser:
         return redirect('/accounts/logout')

templates/checkout/address.html
{% extends "base/base.html" %}

{% block head %}
<style>
    #address-form label {
  display: block;
  margin-bottom: 0.5em;
}

#address-form input,
#address-form select {
  display: block;
  width: 100%;
  padding: 0.5em;
  margin-bottom: 1em;
  border: 1px solid #ccc;
  border-radius: 0.25em;
  box-sizing: border-box;
}

#address-form .form-group {
  margin-bottom: 1.5em;
}

#address-form button[type="submit"] {
  display: block;
  width: 100%;
  padding: 0.5em;
  border: none;
  border-radius: 0.25em;
  background-color: #007bff;
  color: #fff;
  cursor: pointer;
}

#address-form button[type="submit"]:hover {
  background-color: #0062cc;
}
#address-form {
  background-color: #f5f5f5;
  padding: 1em;
  font-family: Arial, sans-serif;
  font-size: 16px;
}
#address-form {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-gap: 1em;
}

#address-form label {
  grid-column: 1 / span 2;
}

#address-form input[type="submit"] {
  grid-column: 1 / span 2;
}

#address-form .form-group:nth-child(odd) {
  grid-column: 1 / span 1;
}

#address-form .form-group:nth-child(even) {
  grid-column: 2 / span 1;
}
.form-group label {
    display: inline-block;
    vertical-align: middle;
    margin-right: 10px;
}

.form-group input[type="checkbox"] {
    display: inline-block;
    vertical-align: middle;
}





</style>
{% endblock %}

{% block offcanvas %}
{% if flag %}
    {% include "base/loggedin.html" %}
    
    {% else %}
    {% include "base/loggedout.html" %}
        
    {% endif %}
{% endblock %}

{% block navigation %}
    
{% include "base/loggedin.html" %}
    
    
{% endblock %}

{% block content %}
 <!-- Breadcrumb Begin -->
 <div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="{% url 'homepage' %}"><i class="fa fa-home"></i> Home</a>
                    <a href="{% url 'checkout' %}">Checkout </a>
                    <span>Add address</span>
                </div>

                </div>
            </div>
        </div>
    </div>
</div>
<section class="checkout spad">
<div class="container">

<div id="address-form" class="row">
    
     <form action="" method="POST">
        {% csrf_token %}
        <div class="col-lg-6 col-md-6 col-sm-6">
            
            <div class="form-group">
                <label for = " ">First Name</label>
                {{form.first_name}}
                {% if form.errors.first_name %}
                    <label for="" class="text-danger">{{form.errors.first_name}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for = " ">Last Name</label>
                {{form.last_name}}
                {% if form.errors.last_name %}
                    <label for="" class="text-danger">{{form.errors.last_name}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-12">
            <div class="form-group">
                <label for = " ">country</label>
                {{form.country}}
                {% if form.errors.country %}
                    <label for="" class="text-danger">{{form.errors.country}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for = " ">address</label>
                {{form.address}}
                {% if form.errors.address %}
                    <label for="" class="text-danger">{{form.errors.address}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for = " ">City</label>
                {{form.city}}
                {% if form.errors.city %}
                    <label for="" class="text-danger">{{form.errors.city}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for = " ">State</label>
                {{form.state}}
                {% if form.errors.state %}
                    <label for="" class="text-danger">{{form.errors.state}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_pincode">Pincode:</label>
                {{ form.pincode }}
                {% if form.pincode.errors %}
                    <div class="invalid-feedback">{{ form.pincode.errors.as_text }}</div>
                {% endif %}
            </div>
            
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for = " ">Phone</label>
                {{form.phone}}
                {% if form.errors.phone %}
                    <label for="" class="text-danger">{{form.errors.phone}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for = " ">Email</label>
                {{form.email}}
                {% if form.errors.email %}
                    <label for="" class="text-danger">{{form.errors.email}}</label>
                {% endif %}
            </div>
            
            <div class="form-group">
                <div class="form-check">
                    {{ form.is_default }}
                    <label class="form-check-label" for="{{ form.is_default.id_for_label }}">Default</label>
                </div>
                {% if form.errors.is_default %}
                    <label class="text-danger">{{ form.errors.is_default }}</label>
                {% endif %}
            </div>
            
            
        </div>
        
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-info text-center ">Save</button>

            </div>
    </form>

</div> 
</div>
</section>
    <!-- <h1>Create an address</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    </form> -->

{% endblock %}

templates/checkout/guestaddress.html
{% extends "base/base.html" %}

{% block head %}
<style>
    #address-form label {
  display: block;
  margin-bottom: 0.5em;
}

#address-form input,
#address-form select {
  display: block;
  width: 100%;
  padding: 0.5em;
  margin-bottom: 1em;
  border: 1px solid #ccc;
  border-radius: 0.25em;
  box-sizing: border-box;
}

#address-form .form-group {
  margin-bottom: 1.5em;
}

#address-form button[type="submit"] {
  display: block;
  width: 100%;
  padding: 0.5em;
  border: none;
  border-radius: 0.25em;
  background-color: #007bff;
  color: #fff;
  cursor: pointer;
}

#address-form button[type="submit"]:hover {
  background-color: #0062cc;
}
#address-form {
  background-color: #f5f5f5;
  padding: 1em;
  font-family: Arial, sans-serif;
  font-size: 16px;
}
#address-form {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-gap: 1em;
}

#address-form label {
  grid-column: 1 / span 2;
}

#address-form input[type="submit"] {
  grid-column: 1 / span 2;
}

#address-form .form-group:nth-child(odd) {
  grid-column: 1 / span 1;
}

#address-form .form-group:nth-child(even) {
  grid-column: 2 / span 1;
}
.form-group label {
    display: inline-block;
    vertical-align: middle;
    margin-right: 10px;
}

.form-group input[type="checkbox"] {
    display: inline-block;
    vertical-align: middle;
}





</style>
{% endblock %}

{% block offcanvas %}
{% if flag %}
    {% include "base/loggedin.html" %}
    
    {% else %}
    {% include "base/loggedout.html" %}
        
    {% endif %}
{% endblock %}
    
{% block navigation %}
    
{% if flag %}
    
{% include "base/loggedin.html" %}
{% else %}
{% include "base/loggedout.html" %}
{% endif %} 
    
    
{% endblock %}


{% block content %}
 <!-- Breadcrumb Begin -->
 <div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="{% url 'homepage' %}"><i class="fa fa-home"></i> Home</a>
                    <a href="{% url 'checkout' %}">Checkout </a>
                    <span>Add address</span>
                </div>

                </div>
            </div>
        </div>
    </div>
</div>
<section class="checkout spad">
<div class="container">

<div id="address-form" class="row">
    
     <form action="" method="POST">
        {% csrf_token %}
        <div class="col-lg-6 col-md-6 col-sm-6">
            
            <div class="form-group">
                <label for="first_name">First Name</label>
                <input type="text" id="first_name" name="first_name" required value="{{address.first_name}}">
                {% if errors.first_name %}
                <label for="first_name" class="text-danger">{{errors.first_name}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for="last_name">Last Name</label>
                <input type="text" id="last_name" name="last_name" required value="{{address.last_name}}">
                {% if form.errors.last_name %}
                    <label for="" class="text-danger">{{form.errors.last_name}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-12">
            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" id="country" name="country" required value="{{address.country}}">
                {% if form.errors.country %}
                    <label for="" class="text-danger">{{form.errors.country}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" id="address" name="address" required value="{{address.address}}">
                {% if form.errors.address %}
                    <label for="" class="text-danger">{{form.errors.address}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="city">City</label>
                <input type="text" id="city" name="city" required value="{{address.city}}">
                {% if form.errors.city %}
                    <label for="" class="text-danger">{{form.errors.city}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="state">State</label>
                <input type="text" id="state" name="state" required value="{{address.state}}">
                {% if form.errors.state %}
                    <label for="" class="text-danger">{{form.errors.state}}</label>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="pincode">Pincode</label>
                <input type="text" id="pincode" name="pincode" required value="{{address.pincode}}">
                {% if form.pincode.errors %}
                    <div class="invalid-feedback">{{ form.pincode.errors.as_text }}</div>
                {% endif %}
            </div>
            
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="phone" required value="{{address.phone}}">
                {% if form.errors.phone %}
                    <label for="" class="text-danger">{{form.errors.phone}}</label>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required value="{{address.email}}">
                {% if form.errors.email %}
                    <label for="" class="text-danger">{{form.errors.email}}</label>
                {% endif %}
            </div>
            
            
            
            
        </div>
        
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-info text-center ">Save</button>

            </div>
    </form>

</div> 
</div>
</section>
    <!-- <h1>Create an address</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    </form> -->

{% endblock %}